version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=$NGINX_HOST
      - NGINX_PORT=$NGINX_PORT
    networks:
      - main
    restart: always

  api:
    build:
      context: ./api
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - SESSION_ID=${SESSION_ID}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - main
      - db
    restart: always
    secrets:
      - credentials.json
    image: bwisniew/intra-tutors-api:latest
  
  app:
    build:
      context: ./app
      args:
        REACT_APP_BACKEND_URL: ${BACKEND_URL}
    networks:
      - main
    restart: always
    image: bwisniew/intra-tutors-app:latest

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - db
    restart: always

volumes:
  mongo-data:

networks:
  main:
    driver: bridge
  db:
    driver: bridge

secrets:
  credentials.json:
    file: ./secrets/credentials.json
